### ISSUE TITLE
Occupancy grid node is missing

### ISSUE THREAD

**Issue by routiful** [ros2/cartographer_ros#23]
I have developed cartographer example with TB3. But the master branch did not include the occupancy_grid_node. How can I get a /map topic to use this?

**Comment by routiful** [comment]
Okay, I will update the code soon. Thanks

**Comment by routiful** [comment]
I fetched the cartographer and cartographer_ros into release-1.0 branch and update ros2 api.
But i got stuck some problems. I opened issues in cartographer_ros repo. 

https://github.com/googlecartographer/cartographer_ros/issues/1151

Do you have any comments? @clalancette

**Comment by clalancette** [comment]
The short answer is that we have not kept cartographer up-to-date with ROS 2 crystal.  The last version we know for sure this port worked on is ROS 2 Ardent, and we haven't done updates on it since then.  Probably the correct thing to do here is work with the upstream https://github.com/googlecartographer/cartographer_ros to do a maintained ROS 2 port of cartographer in a separate branch on that repo, using some of the work we did here as a reference.

**Comment by routiful** [comment]
I opened PR.
https://github.com/ros2/cartographer_ros/pull/25

**Comment by clalancette** [comment]
This was fixed by the update to the 1.0.0 and additional work (thanks @routiful ), so I'll close this out.
